# Generated by Django 5.0.3 on 2025-04-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsci551", "0002_userqueryhistory"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="customer_id",
        ),
    ]
