# Generated by Django 5.0.3 on 2025-04-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dsci551", "0003_alter_order_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table=None,
        ),
    ]
